#!/bin/bash
killall trayer
trayer --edge top --align right --widthtype pixel --width 256 --SetDockType true --SetPartialStrut true --transparent true --alpha 0 --tint 0x000000 --expand true --heighttype pixel --height 16 --margin 214
